### PR TITLE
Feature new icons

### LINKED ISSUE #406: Icon Request: test/spec JS
- I'm using Visual Studio Code Version [1.6.1] [Stable]
- I'm using the extension version [3.0.6]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Windows] [x64]
- [x] I'm sure this issue is not a _duplicate_?
- [x] I want to create an icon request:
  - Type: extension
  - Icon Name: Test/Spec
  - Extensions: .test.js, .spec.js
  - [x] I crossed out "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**

I keep test files ending with .spec.js in the same folder as the source files; having an icon for test files, in addition to folders, would be very helpful.
I can't think of an icon to use for this, I trust you can come up with a good one.

### PR DESCRIPTION
**Pull request by robertohuertasm**
***Fixes #406, #409***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] I've pulled the latest master branch
* [x] I've run `npm install` to install all the dependenies
* [x] I've checked my code, it is clean.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] My pull request is not too big, otherwise I've already squashed it.
* [x] I've run `npm run build` to build the extension. (If I had done something with the extension.)

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Simply Beautiful :)

**Comment by robertohuertasm** [comment]
It should be working... at least it's working for me. @jens1o can you confirm that you see the changes?
@kristianmandrup you have the icons correctly set? I mean, the file icon theme that it's selected it's vscode-icons, isn't it?

**Comment by robertohuertasm** [comment]
@kristianmandrup which version of VSCode are you using?

**Comment by jens1o** [comment]
Just a moment...

**Comment by jens1o** [comment]
Working for me.

**Comment by robertohuertasm** [comment]
I have no idea what may be happening. Try reinstalling the extension. Is it the extension disabled?

**Comment by kristianmandrup** [comment]
Works now! Turns out I had installed multiple different icon plugins and was using the Seti themes.
Now it looks beautiful :) Thanks a lot

**Pull request merged**
