### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by jens1o**
If the file format or anything else is wrong, please let me know.

Anyway, you have to implement this, because I don't know how your wishes are.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@jens1o you're right. We have to think how we're going to handle this in detail. You're too fast man! :grin: And I'm too busy to follow your path! :disappointed: :stuck_out_tongue_winking_eye:

**Comment by jens1o** [comment]
Summer holidays ^^ Take your time, but can't say that you don't have something to do ;)

**Comment by jens1o** [comment]
Summer holidays ^^ Take your time, but can't say that you don't have something to do ;)

**Comment by jens1o** [comment]
Summer holidays ^^ Take your time, but can't say that you don't have something to do ;)

**Comment by jens1o** [comment]
Summer holidays ^^ Take your time, but can't say that you don't have something to do ;)

**Pull request merged**
