### PR TITLE
Add the Flash icon for .swf, .swc and .sol

### PR DESCRIPTION
**Pull request by Gama11**
.sol is a local shared object, aka flash cookie

Didn't update icons.zip to avoid merge conflicts with the other PRs.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
It's ok but I would rather make the icon smaller. Let's put some space between the border and the icon. Let's standarize it in 2 pixels of margin as per some other icons in the extension. [#193](https://github.com/robertohuertasm/vscode-icons/pull/193)

**Comment by jens1o** [comment]
@robertohuertasm Okey.

**Comment by Gama11** [comment]
The HaxeDevelop icon I added also didn't have any margins I think. Neither did Lime really (#182), but I don't think it's necessary there?

**Comment by robertohuertasm** [comment]
I don't think so, don't worry about them. In fact, your lime icon had more than 2px margin although only vertical. It's not a common rule because most of the icons that we currently have are not equal but just to make the icons feel more or less right with the others that we have. If we're making a square icon full 32px it's going to be seen as bigger. It's more a perceptive issue than numeric. @jens1o @Gama11

**Comment by Gama11** [comment]
I have actually noticed that the HaxeDevelop icon appears bigger than the others, so I'd like to change that one.

**Comment by Gama11** [comment]
Done!

**Comment by jens1o** [comment]
You need to also add them to the icons.zip.

**Comment by Gama11** [comment]
As mentioned previously:

>Didn't update icons.zip to avoid merge conflicts with the other PRs.

**Comment by jens1o** [comment]
Oh, I overlooked this notice. But you could create a new branch, in which you update the zip file.

**Comment by Gama11** [comment]
What would that do?

**Comment by jens1o** [comment]
A branch is a split of your fileset, in which you can change files, because it is a copy of the master branch. When you change a file in there, it does not affect the other branches. You can create for every branch one PR, and if you commit something to this branch, it does not affect others.

**Comment by jens1o** [comment]
You can create a new branch, which does not affect the other files.

**Comment by Gama11** [comment]
I'm well aware of that. I'm actually trying to avoid creating merge conflicts with your PRs, not my own.

**Comment by jens1o** [comment]
I thought it just add or remove them? In a zip, it would add them, don't it?

**Comment by Gama11** [comment]
Hm.. I thought Git might just treat .zip as a binary file. Maybe not!

**Comment by robertohuertasm** [comment]
@Gama11, @jens1o I'm not really sure about this either so I've changed the code and now icons.zip is just a build artifact. Every time anyone runs build task icons.zip file will be created from icons folder. :grin:

**Comment by jens1o** [comment]
Nice thing! :heart:

**Comment by Gama11** [comment]
Awesome!

**Pull request merged**
