### PR TITLE
paket Icon

### LINKED ISSUE #188: Icon request : Paket
I want to create an icon request for [Paket](http://fsprojects.github.io/Paket/)

Icon Name: paket

Sample original Icon: https://dl.dropboxusercontent.com/u/11302680/logo.png

Extensions:

- paket.dependencies
- paket.lock
- paket.references
- paket.template
- paket.local

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #188***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [ ] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

adds paket

### CODE REVIEW

**Comment by robertohuertasm** [comment]
There several things here:
1. The icon inside the zip is name packet not paket, so the icon is not found when enabled.
2. The icon has not any margin and it's too big compared to the rest.
3. The supported file extensions is not correctly set: i.e. you're using dependencies as a extension but this will cause all kind of files ended in dependencies to be using the paket icon and that's not what we want. We want to be only enabled when the file name is paket.dependencies.

In order to do so, the process is a little bit cumbersome. As this is a special case you'll have to create a line for every complex extension. Following with our previous example:
```json
{ icon: 'paket', extensions: ['paket.dependencies'], special: 'dependencies' },
// and so on ...
```

**Comment by jens1o** [comment]
> you're using dependencies as a extension but this will cause all kind of files ended in dependencies to be using the paket icon and that's not what we want. We want to be only enabled when the file name is paket.dependencies.

Again, thanks for the headus up, this was my problem too.

**Comment by jens1o** [comment]
Is that margin okey right now @robertohuertasm?

**Comment by robertohuertasm** [comment]
Ok! Now just the supported extension file remains to be changed before merging :wink:

**Comment by jens1o** [comment]
I just wanted to ask, I'll push in a few minutes.

**Comment by jens1o** [comment]
Could you please look wether anything is right? Double Check is better, I think.

**Comment by robertohuertasm** [comment]
It seems that everything is ok! :+1:

**Comment by jens1o** [comment]
Closed? What?

**Comment by robertohuertasm** [comment]
I don't know what happened... It's already merged but somehow github wouldn't recognize it. It's on the changelog anyway :wink:

**Comment by jens1o** [comment]
merged with f4c62922

**Pull request closed without merging**
