### PR TITLE
Add support for Swift "Package.pins".

### LINKED ISSUE #513: Icon for new Swift Package Manager file - Package.pins
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: SwiftPM Package.pins
      - Icon Name: SPMPins
      - Sample original Icon(32x32/svg/transparent whenever possible): Standard Swift icon
      - Extensions: .pins (but for just Package.pins file)

There is new file created by Swift Package Manager called Package.pins. Please add standard Swift icon for this file. Thanks.

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #513***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

### CODE REVIEW

**Comment by jens1o** [comment]
Where's the icon?

**Comment by JimiC** [comment]
It extends the use of `Swift` icon to the filename.

**Comment by jens1o** [comment]
Ah, I thought  we'll create a new icon for it.

**Comment by JimiC** [comment]
From @rbukovansky
> There is new file created by Swift Package Manager called Package.pins. Please add standard Swift icon for this file. Thanks.

**Comment by jens1o** [comment]
Okey.

**Pull request merged**
