### PR TITLE
Updating golang gopher icon to blue gopher

### PR DESCRIPTION
**Pull request by xmattstrongx**
Adding in chubby blue gopher icon for golang projects :)

image

### CODE REVIEW

**Comment by xmattstrongx** [comment]
#111

**Comment by mysticman** [comment]
Looks very good nice job ;)

**Comment by robertohuertasm** [comment]
@xmattstrongx I've reduced a little bit the gopher as it was using all the 32x32 space without any margins. I intend to publish it today. Many thanks for this PR! 😄

**Comment by robertohuertasm** [comment]
Already published! 👍

**Comment by xmattstrongx** [comment]
@robertohuertasm cool. Thanks for allowing the update! Blue gopher is deifintely much more relatable to the file.

**Pull request merged**
