### PR TITLE
add Webpack

### LINKED ISSUE #305: Add webpack support
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: png
      - Icon Name: webpack
      - Sample original Icon(32x32/png/transparent whenever possible): [icon](https://topheman.github.io/webpack-babel-starter/assets/974262647c82057b6078c432841a53ea.png)
      - Extensions: webpack.config.js

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #305***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [X] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

adds webpack.

@robertohuertasm Is it right like this?

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@jens1o it's ok! Sorry for the delay in my answer. I'm a little busy these days... :disappointed:

**Comment by jens1o** [comment]
Don't worry :smiley:

**Comment by wgruis** [comment]
webpack.config.dev.js or webpack.config.*.js not support

**Comment by jens1o** [comment]
@wgruis Look here: https://github.com/robertohuertasm/vscode-icons/issues/313#issuecomment-247356862

**Pull request merged**
