### PR TITLE
Added dockerignore ext and build using Docker

### LINKED ISSUE #303: Add .dockerignore to docker icon

### PR DESCRIPTION
**Pull request by FrenchBen**
***Fixes #[ISSUE]***
Fixes #303

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] I've pulled the latest master branch
* [x] I've run `npm install` to install all the dependenies
* [x] I've checked my code, it is clean.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] My pull request is not too big, otherwise I've already squashed it.
* [x] I've run `npm run build` to build the extension. (If I had done something with the extension.)

[short comment]
This adds support for the `.dockerignore` extension but also introduces a `Dockerfile` to build the code using docker, preventing any npm errors and install on the user's local system.

ps: I'm not sure how the icons.json file got created or modified - Is this from the `npm run build`?

### CODE REVIEW

**Comment by jens1o** [comment]
Regarding your question: Yes, it is from ```npm run build```.

**Comment by FrenchBen** [comment]
@jens1o I saw it in the code, but not understanding how it's used?

**Comment by jens1o** [comment]
It is used for the legal way of providing our icons. VS Code uses this icons.json to look for all extensions provided by us.

**Comment by FrenchBen** [comment]
@jens1o is there a reason it's not part of the distribution folder like the other scripts?

**Comment by jens1o** [comment]
Yes, because this file is for vscode(and not for building the extension), and **shouldn't** be touched by anyone.

**Comment by FrenchBen** [comment]
@jens1o Maybe I'm missing the part of what gets loaded by vscode and how it does it... (n00b I know)

**Comment by jens1o** [comment]
It is referenced in the ```package.json```. Look [here](https://github.com/robertohuertasm/vscode-icons/blob/master/package.json#L99-L105)

**Pull request merged**
