### PR TITLE
Icon xliff

### LINKED ISSUE #316: Icon request: XLIFF language translation files
**Checklist**

- I'm using Visual Studio Code Version [1.5.2] [Stable]
- I'm using the extension version [2.0.5]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Ubuntu 16.04] [amd64]
- [x] I'm sure this issue is not a *duplicate*.
- [x] I want to create an icon request:
      - Type: icon
      - Icon Name: XLIFF
      - Sample original Icon: [http://www.flaticon.com/free-icon/planet-earth_178354#term=globe&page=1&position=25]
      - Extensions: .xliff, .xlf
      - [x] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description**

This would be a good icon to represent the translation files in the XLIFF format.

### PR DESCRIPTION
**Pull request by aalaap**
***Fixes #316***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [x] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

Adds the globe icon for the XLIFF language translation format files.

Icons made by [Freepik](http://www.flaticon.com/authors/freepik "Freepik") from [www.flaticon.com](http://www.flaticon.com "Flaticon") is licensed by [CC 3.0 BY](http://creativecommons.org/licenses/by/3.0/ "Creative Commons BY 3.0")

### CODE REVIEW

**Comment by jens1o** [comment]
Ha. I am not in friendship with this new github feature, I cannot correct myself... Okey, then the updated icon is left.

**Comment by aalaap** [comment]
@jens1o I've made the requested changes. What's the next step in this new GitHub reviews way?

**Comment by aalaap** [comment]
@jens1o Yeah, it's a bit confusing. I've added the icon as well now.

**Comment by jens1o** [comment]
Perfect, our way to go! Will be merged as soon as @robertohuertasm is there :smile:

**Comment by aalaap** [comment]
@jens1o Awesome! :party:

**Pull request merged**
