### PR TITLE
Support license files with an .md extension

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Gama11** [comment]
Btw, there seem to be a few `extensions` that start with a dot.. For instance the `eslint` ones. Didn't you mention that there shouldn't be a leading dot?

**Comment by robertohuertasm** [comment]
@Gama11if you omit the  dot then you will allow: `eslintrc.yml`, note that no dot is placed at the beginning of the file name. By using the dot you're inforcing the user to, at least, start the filename with a dot. If you don't care about this then by omitting the dot you provide more options to associate files to a specific icon.

**Comment by Gama11** [comment]
Any way to make this case-insensitive in order to support variations like `LICENSE` and `LICENSE.md`?

**Comment by robertohuertasm** [comment]
As far as I know it should be case insensitive already? is it not working for you?

**Comment by Gama11** [comment]
No. Uppercase:



Renamed to lowercase:

**Comment by Gama11** [comment]
No:





Also, I guess different spellings should be considered (license vs licence), but that's a different issue.

**Comment by robertohuertasm** [comment]
Fixed in #264

**Comment by Gama11** [comment]
Awesome, thanks! :)

**Pull request merged**
