### PR TITLE
Added Kotlin Icon

### PR DESCRIPTION
**Pull request by Jonatino**
**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch.
* [X] I've run `npm install` to install all the dependencies.
* [X] I've run ESLint.
* [ ] My pull request fixes an issue, I referenced the issue.
* [X] I've run `npm run build` to build the extension.

Noticed Kotlin icon was missing, so though I'd help out :)

### CODE REVIEW

**Comment by JimiC** [comment]
Is there any chance you can provide the SVG version for the icon (as we are in the process of converting all icons to that format)?

**Comment by jens1o** [comment]
I agree with @JimiC. Since we switched from png, I don't want png again. SVG is just perfect ;)

**Comment by Jonatino** [comment]
Here you go. Cheers.

@JimiC @jens1o 
[kotlin.zip](https://github.com/robertohuertasm/vscode-icons/files/601656/kotlin.zip)

**Comment by JimiC** [comment]
@Jonatino Thanks, but the point is to add it with a commit to the PR.

**Comment by robertohuertasm** [comment]
@Jonatino @JimiC I take care of the svg

**Comment by jalmansa88** [comment]
.kt files are not working for me. Using VS Code Icons.

**Comment by robertohuertasm** [comment]
you just need to install some `Kotlin` extension like [this](https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin)

**Comment by jalmansa88** [comment]
Does it necessary to install the KotlinLang plugin to see the Kotlin .kt file ico?

**Comment by JimiC** [comment]
Yes. The extra benefit to it is that you will get also syntax highlighting for `Kotlin`. I can't imagine any dev using a programming language without syntax highlighting.

**Comment by jalmansa88** [comment]
Works fine after installing the plugin.
I am not developing in Kotlin atm, just was checking the pluging with differentes extensions. With Go works without installing anything else.

Thanks for your support.

**Comment by JimiC** [comment]
`Go` is natively supported by `vscode` (https://github.com/Microsoft/vscode/tree/master/extensions/go).

**Pull request merged**
