### PR TITLE
reduced a little ts and js icons

### PR DESCRIPTION
**Pull request by robertohuertasm**
They look a little bit bigger than I expected.

### CODE REVIEW

**Comment by tmueller** [comment]
Hi,

is it possible to bring back the orgiginal icons of js and ts, that were introduced in #509? They looked so much better than the current ones.

Thanks,
Thomas

**Comment by robertohuertasm** [comment]
Hi @tmueller, some people have been complaining of the official icons. They were claiming they were to much obstrusive so we have decided to make a rollback for the moment while we're preparing a user customization tool. We're going to deliver it in phases so it will be improving. First version will be have some presets so you can decide if you want to use the official ones or not, among other things. See #537, #514

**Comment by tmueller** [comment]
Thanks for your quick reply. It's a pity other users found them to obstrusive. Boils down to personal likes I guess. Looking forward to the costumization tool.

**Comment by robertohuertasm** [comment]
I've have a very rough version. I guess I will be able to provide something during the week. 😉

**Comment by infinnie** [comment]
I want the new icons back…

**Comment by JimiC** [comment]
@robertohuertasm FACEPALM

**Pull request merged**
