### PR TITLE
new riot tag icon

### PR DESCRIPTION
**Pull request by mysticman**
just a little enhancement

thanks for the extension very much

sample

### CODE REVIEW

**Comment by jens1o** [comment]
Could you please modify the margin at the bottom? It is way too much down, not actually centered.

**Comment by mysticman** [comment]
Hi I've patched the icon, now you can see the exact result.

sample-patched
sample-patched-ruler

**Comment by robertohuertasm** [comment]
@mysticman good work! 😉

**Comment by robertohuertasm** [comment]
Merged and published in 1.4.5

**Pull request merged**
