### PR TITLE
add spec and test icons for .spec.js and .test.js file types

### PR DESCRIPTION
**Pull request by kristianmandrup**
***Fixes #[306]***

**Changes proposed:**
* [x ] Add `spec` and `test` file and icon types

**Things I've done:**
* [x ] I've pulled the latest master branch
* [x] I've run `npm install` to install all the dependencies
* [x] I've checked my code, it is clean.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] My pull request is not too big, otherwise I've already squashed it.
* [x] I've run `npm run build` to build the extension. (If I had done something with the extension.)

File with replacements successfully created!
icon contribution file successfully generated!
Build completed!

Just not sure yet how to test it in VSC, but icons were saved from Photoshop in 24x24 PNGx2 and are named according to conventions. File mapping should also be in place correctly at `supportedExtensions.js`

```
    { icon: 'test', extensions: ['test.js', 'test'] },
    { icon: 'spec', extensions: ['spec.js', 'spec'] },
```

Please advice if I missed anything.

PS: might make sense with an `e2e` icon for `.e2e.js` (E2E tests) as well!?

### CODE REVIEW

**Comment by kristianmandrup** [comment]
I tried to make it work locally, but so far no success.

When I run `npm run build` I can see my `icons.zip` is updated, but the icons I've added are not in the zip!? Please advice ;)

I also configured my user settings to point to my local `icons.zip` file.

// Place your settings in this file to overwrite the default settings

```
{
    "editor.tabSize": 2,
    "vsicons.icons": "/Users/kristianmandrup/repos/node-libs/vscode-icons/icons.zip"
}
```

**Comment by kristianmandrup** [comment]
I now created 32x32 @x2 PNG icons using Photoshop, but they still don't show up locally when I try to test them. What do you mean by lower it a pixel? 31x31?

**Comment by jens1o** [comment]
32 x 32 is the size. Then center the icon with a 2pixels margin. And **then**, you lower the icon itself a pixel.

**Comment by kristianmandrup** [comment]
Sorry, first time I try to design icons. I'm a developer not a graphic designer. Trying my best to learn. Don't know how to center and lower one pixel. Beyond my skill level.
I pushed new commit with psd files included. Please help me out ;) Thanks!

**Comment by robertohuertasm** [comment]
@kristianmandrup don't worry, I was already preparing icons for these cases. i will take care of it.

**Comment by kristianmandrup** [comment]
@robertohuertasm Thank you so much!! :)

**Pull request closed without merging**
