### PR TITLE
add prolog

### LINKED ISSUE #383: Icon Request: Prolog
SwiProlog has a nice logo https://en.wikipedia.org/wiki/File:Swipl.png

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #383***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [X] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

adds prolog support

### CODE REVIEW

**Comment by jens1o** [comment]
Wait, it isn't transparent...

**Comment by robertohuertasm** [comment]
F**k, I already merged it 😂 
I'll wait for your new pr with the image changed.

**Comment by raztd** [comment]
the logo with transparent background http://i.imgur.com/F9TSqHi.png

**Comment by jens1o** [comment]
Thank you! :D I was that frustated...

**Comment by raztd** [comment]
Resized to 32 x 32 http://i.imgur.com/pP7FhGa.png

**Comment by jens1o** [comment]
@raztd thanks, but it's already corrected.

**Pull request merged**
