### PR TITLE
Added .yarnclean to matches

### PR DESCRIPTION
**Pull request by wagerfield**
Added `.yarnclean` extension matching.

Sorry this wasn't in my last PR...I didn't know about it! 

[Details here](https://yarnpkg.com/en/docs/cli/clean).

### CODE REVIEW

**Comment by jens1o** [comment]
I think he build it iself @robertohuertasm

**Comment by wagerfield** [comment]
@robertohuertasm good to know—I tried to figure out what files I was supposed to modify, but it wasn't that obvious, so I just searched the project for other files to see where they were defined. Perhaps elaborate a little more in the contributing section of the README?

Thanks for the rapid merges 😃

**Comment by wagerfield** [comment]
@robertohuertasm would it be possible to publish a new release with the yarn icons included?

...I'm keen to see them in VSCode 😃

**Comment by robertohuertasm** [comment]
@wagerfield you got it. 3.0.5 is out!

**Pull request merged**
