### PR TITLE
add photoshop

### LINKED ISSUE #191: Icon Request: .psd
- [X] I want to create an icon request(if not, remove these lines below):
      - Icon Name: Photoshop
      - Sample original Icon(32x32/png/transparent whenever possible): We could use the "Ps"-Font. It is simple and looks cool.
      - Extensions: .psd
      - [X] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

image
Do you see the failure? This is the official repo, and not any file in our repo has got an icon? A shame!

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #191***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [ ] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

add psd files

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@jens1o can we make this icon a little bit smaller? You're using the 32x32 without leaving any margin and looks a little bit bigger than the other ones.

**Comment by jens1o** [comment]
What's the standard margin? There are no informations for that.

**Comment by robertohuertasm** [comment]
You're absolutely right. Take a look at #200 2px

**Comment by robertohuertasm** [comment]
@jens1o still to PR pending. Let me know when they're ready to merge :wink:

**Comment by jens1o** [comment]
I'd forget, sorry. Coming now.

**Comment by jens1o** [comment]
ready

**Pull request merged**
