### PR TITLE
Add HaxeDevelop icon for .hxproj files

### PR DESCRIPTION
**Pull request by Gama11**
HaxeDevelop is a very popular IDE for Haxe. It uses .hxproj as the extension for its Haxe project format.

This is it from me for now. ;)

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Published all your PRs right now in 1.7.3. Thanks for your great work @Gama11!

**Comment by Gama11** [comment]
Thank you for the great extension! :)

Is .gitkeep working for you? I get a generic file icon there, hm...

**Comment by robertohuertasm** [comment]
it's working locally...

**Comment by Gama11** [comment]
Must've been something wrong locally. I switched from the git version to the official one from the extension installer again and it works now. :+1:

**Comment by robertohuertasm** [comment]
I've tried the released one recently installed from the marketplace and it's working! Thanks for this! :+1:

**Pull request merged**
