### PR TITLE
Add Emberjs icon support.

### LINKED ISSUE #420: [Icon Request] Ember
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*
- [x] I want to create an icon request:
      - Type: [.ember-cli]
      - Icon Name: [ember]
      - Sample original Icon(32x32/png/transparent whenever possible): [N/A]
      - Extensions: no extension

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #420***

**Changes proposed:**
* [x] Add

**Things I've done:**
* [x] I've pulled the latest master branch.
* [x] I've run `npm install` to install all the dependencies.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] I've run `npm run build` to build the extension.

**Icon:** file_type_ember 2x

**Preview:**screen shot 11-06-16 at 01 48 pm

### CODE REVIEW

**Comment by JimiC** [comment]
This PR may have conflicts if #419 gets accepted.

**Comment by robertohuertasm** [comment]
Hi Jimmy, is it .ember-cli a complex extension or a file name?

**Comment by JimiC** [comment]
Actually it's a filename with no extension to configure the ember cli.

**Comment by robertohuertasm** [comment]
Then I think it's not properly set. You have to add `contribType: ctype.filename` to the icon declaration.

**Comment by JimiC** [comment]
That's what I thought too but was not sure. I got confused cause `.editorconfig` is also a config filename with no extension and it doesn't have the `contribType`.

**Comment by robertohuertasm** [comment]
Then it's a bug, too. The thing is that it will work as a filename if you don't mark it as VSCode will thing of it as a complex extension without file name. But it would be nice to put the filename attribute in order to make it explicit and not allow xxx.editorconfig as a editorconfig file with its icon.

**Comment by robertohuertasm** [comment]
Let me know when your change is done and I will merge it gladly and deploy it tomorrow 😉

**Comment by JimiC** [comment]
OK. I'll get over all entries and fix whatever I find.

If I understood it correctly, basically the rules are:
fileExtensions: any file extension declaration.
fileNames: any file name or specific filename with extension.

Is that right?

**Comment by jens1o** [comment]
I think so @JimiC

**Comment by JimiC** [comment]
@robertohuertasm Give a minute I'm working on it.

**Comment by JimiC** [comment]
@robertohuertasm Done.

**Comment by robertohuertasm** [comment]
Thanks @JimiC!

**Comment by JimiC** [comment]
😄

**Pull request merged**
