### PR TITLE
Just making sure that the grammar is right.

### PR DESCRIPTION
**Pull request by Kitanga**
I just went through and made sure that the grammar was OK. Your message was kept intact. By the way, thank you for this extension!!!!

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@Kitanga, thank you very much for these corrections. It's always a good thing to have a native speaker overviewing what we, non-English natives, write. 👍

**Comment by Kitanga** [comment]
Your welcome! Btw, I'm technically a non-English native, according to the English Native haha.

Anyways, I was wondering what software you all use to create these icons?

**Comment by robertohuertasm** [comment]
We're using Adobe Illustrator and/or Inkscape.

**Comment by JimiC** [comment]
@Kitanga I'm in the process of writing a "How to" for Illustrator and Inkscape. It will be published soon(TM).

*soon(TM): For those who don't get it, it's a play on words, meaning "sooner than never".

**Comment by jens1o** [comment]
@JimiC HERE. Inkscape, perfect. I'm too silly for it. 😆

**Comment by Kitanga** [comment]
Well I've used Inkscape very little.
What about using GIMP?

**Comment by JimiC** [comment]
AFAIK GIMP has no native support and requires a plugin. Not ideal. Correct me if I'm wrong.

**Pull request merged**
