### PR TITLE
Added VS Code icons to files.

### PR DESCRIPTION
**Pull request by davormas**
Added extensions.json and settings.json as VS Code files.

### CODE REVIEW

**Comment by jens1o** [comment]
Please do not modify this file. Go ahead into the build directory, there is a file called ```supportedExtensions.js``` Please add it there, thanks 😃

**Comment by robertohuertasm** [comment]
settings.json is not only a vscode related file so I think it shouldn't be changed. 

extensions.json could follow the same rationale, but I'm not as certain.

**Comment by robertohuertasm** [comment]
I would directly close this PR. What do you think @jens1o, @JimiC?

**Comment by JimiC** [comment]
I agree with your reasoning. `settings.json` isn't in any way affiliated with `vscode`.

**Comment by jens1o** [comment]
I agree, too. Closing this.

**Pull request closed without merging**
