### PR TITLE
add BridleNSIS support

### PR DESCRIPTION
**Pull request by idleberg**
***Fixes #[ISSUE]***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [ ] My pull request fixes an issue, I referenced the issue.

[short comment]

### CODE REVIEW

**Comment by JimiC** [comment]
I'm under the impression that this may require its own icon or a composite icon with `NSIS` on the background, just to visualize the difference between them.

**Comment by idleberg** [comment]
There is no difference between a `.nsi`, `.nsh`, `.bbnsi` and `.bbnsh` file, they are all vanilla NSIS. Native BridleNSIS uses the extensions `.bnsi` and `.bnsh`. Once transpiled, the resulting files are name `.bbnsi` and `.bbnsh` – only the developer of BridleNSIS knows why that is.

**Comment by JimiC** [comment]
@idleberg I'll take your word for it, judging by the fact that you have more experience working with `BridleNSIS` than me.

**Comment by JimiC** [comment]
@idleberg Are you planning or is there a `BridleNSIS` for `vscode`?
I see you have made one for `Atom` and `SublimeText`.

**Comment by idleberg** [comment]
I have just finished polishing the Atom package, next up is porting it to Visual Studio Code. It will likely be part of the `vscode-nsis` package.

**Comment by robertohuertasm** [comment]
Already implemented in #602.
Credits will be present in the `Changelog`

**Pull request closed without merging**
