### PR TITLE
add the new brighter .scss icon

### PR DESCRIPTION
**Pull request by mysticman**

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Thanks @mysticman, you're the man! 😄

**Comment by robertohuertasm** [comment]
By the way, there's something happening with your profile. Emil Geredy appears, who I guess is you, but Github shows a warning about unrecognised profile. Are you aware of this?

**Comment by robertohuertasm** [comment]
Already published in 1.5.1

**Comment by mysticman** [comment]
I don't know what is the problem with my profile, now I filled some account details and personal info. Is it ok now?

**Comment by robertohuertasm** [comment]
screen shot 2016-07-27 at 09 53 09

**Comment by mysticman** [comment]
Ahh, I dont know how the github get to know my work email, but bow I added to this account and verified. Now?

**Comment by robertohuertasm** [comment]
Now it seems to be good! 👍

**Pull request merged**
