### PR TITLE
converted several PNGs to SVGs

### PR DESCRIPTION
**Pull request by ginfuru**
**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* added svgs
- blade/laravel
- babel
- ansible
- actionscript
- bower
- added bower_mono to match png
- apid
- sass
- scss
- yarn
- webpack
- node
- npm
- gulp
- git
- markdown

nothing special just added SVGs did not edit any of the code base.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @ginfuru, many thanks for this. Unfortunately, I cannot accept the PR at the moment because the icons you provided don't follow the specifications that we need. Maybe @JimiC can use some of them as a base... Let's see what he says. :grinning:

**Comment by ginfuru** [comment]
@robertohuertasm I'll rework the SVGs to match the spec... Sorry thought that it was only for the PNGs.

**Comment by JimiC** [comment]
@ginfuru Thanks for your work. Some of the icons we already have but haven't deploy them yet. The re rest need some further modifications in order to comply with our specs. I'll do them and update yours.
Don't worry though credits will be awarded.

P.S. Hopefully with Holiday Season vacations around the corner, I'll find the time to write that (darn) guide.

**Comment by JimiC** [comment]
All images have been modified an awaiting #563 to be merged in order to submit a new PR on behalf of @ginfuru

**Comment by ginfuru** [comment]
@JimiC Thanks for the credit... I'll make sure to follow the spec for the next conversion.

**Comment by jens1o** [comment]
> I did want to confirm that 32x32 is the ideal dimensions?

Yeah.

**Comment by JimiC** [comment]
I missed the `gulp` icon. Will add it later in the day and make a PR.

**Comment by robertohuertasm** [comment]
@JimiC, please let me know if I'm wrong but as per my understanding, this PR can be closed and you'll submit a PR on behalf of @ginfuru, is that right?

**Comment by JimiC** [comment]
Yeap.

**Pull request closed without merging**
