### PR TITLE
Add support for purescript.

### LINKED ISSUE #431: Icon Request: PureScript
- I'm using Visual Studio Code Version [1.7.1] [Stable]
- I'm using the extension version [4.0.0]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Windows] [x64]
- [x] I'm sure this issue is not a _duplicate_?
- [x] I want to create an icon request:
  - Type: extension
  - Icon Name: PureScript / PureScript Test/Spec
  - Extensions: .purs, .spec.purs, .test.purs
  - [x] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #431***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] I've pulled the latest master branch.
* [x] I've run `npm install` to install all the dependencies.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] I've run `npm run build` to build the extension.

### CODE REVIEW

**Comment by JimiC** [comment]
Has the same colors as `ansible`.

**Comment by jens1o** [comment]
not really on a high-contrast monitor...

**Comment by JimiC** [comment]
What you mean?

**Comment by jens1o** [comment]
I think the background of the logo is quite more dark than the Code background color.

**Comment by JimiC** [comment]
So is the [logo](https://github.com/purescript/logo/blob/master/PS_Logo_Final.svg).

**Comment by jens1o** [comment]
Okey.

**Comment by robertohuertasm** [comment]
Hi @JimiC, I think this is a perfect case for the new light support functionality. I personally don't like the idea of having the squared background like this. Is too similar to the vscode background but different enough to notice the change in the tonality. I would remove it or sorround it with a 1px border of a more lighter tone so users could notice the difference. In this case I do think the logo background is important so I would opt for the second option. What do you think?

**Comment by jens1o** [comment]
By the way, who's "Nooknok"? When I try to visit his profile, I see a 404 error page...

**Comment by JimiC** [comment]
As I said to @jens1o the icon has the same background as the `ansible` icon and those colors are the official ones of the logo. On a light theme colors can be swapped. I don't we need to do any extra work for the time being.

**Comment by JimiC** [comment]
@robertohuertasm I love the idea of having a `light` version and with the work we are doing converting all icons to SVG it can be easily done. But first we need to finish the first task.

**Comment by robertohuertasm** [comment]
After having done a few tests and seen the [purescript github page](https://github.com/andyarvanitis/purescript-native/blob/master/README.md), the [official page](http://www.purescript.org/) and what [google has to say](https://www.google.es/search?q=purescript+logo&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_oMmB1snQAhXMxYMKHcn-BLIQ_AUICCgB&biw=1920&bih=935) I would discard the background square. 

I will try to explain my statement:

1. I think that the logo with the background that we have in this PR doesn't respect the margins in the "official" logo. I know this is because we want to better see the icon inside the square but, in my opinion, this doesn't look good, it seems forced. The alternative, being making the icon smaller doesn't work in our favour either, because the icon is barely recognizable.

2. After seeing some of the Purescript resources I think that the icon is the main piece of the logo. They even use the icon on itself without any background. I think this background is just the contrasted version they use but given that VSCode dark theme has a similar background I think we could take advantadge of that. This would allow us to make the icon look bigger and be close to the "official" way. We're not always accurate  or loyal to the original implementation (see markdown, js, ts...)
image

3. @JimiC, you're right about the Ansible icon. First thing about this icon is that the A should be white. I will change it asap. The other thing to remark, in contrast with the Purescript logo is that in Ansible the Circle is a piece of the icon so it makes sense to incorporate it. It's not like that in the case of Purescript.

Finally, about the `light` version, I think it can be implemented no matter the state of the SVG conversion process. What I mean when I talk about a light version is not that we're going to provide a light version for all the icons at once. I'm talking about implementing a way to mark the icons with a light version flag in the `supportedExtensions`file and generate the proper `icons.json`file. There's already some people who is using the light version with our theme extension. In this case, I was thinking that maybe this could be a way to force us to implement this automatic process by the virtue of having this new icon amongst us. The real light icons implementation would come later. But indeed it's not my idea to force anything so never mind!

**Comment by JimiC** [comment]
@robertohuertasm In the SVG version the A is white for the `ansible`logo. When I worked on the `purescript` logo what troubled me was that it's white and on the artboards white background it doesn't show. I CAN make the logo be only the white parts and amke it 30x30 on the 32x32 canvas.
The problem is that it will not show on a `light` them.

So until we have support for `light` theme we can go with this and revise it later.

**Comment by JimiC** [comment]
I suggest you make your priority to implement the support of a `light` version of an icon and let me do the adjustments on the icons.

Now that I'm familiar with the tool I use to create the icons the process can speed up.

**Comment by robertohuertasm** [comment]
@JimiC ok! You've made your point. Let's do it like you say. Once the light version functionality (#392) is ready this will be the first icon to convert 😉

**Comment by JimiC** [comment]
@robertohuertasm And the `ansible` too.

**Pull request merged**
