### PR TITLE
Adding config icon for config files and binary for pdb

### PR DESCRIPTION
**Pull request by MarcosMeli**
**Changes proposed:**
* [x] Add

**Things I've done:**
* [x] I've pulled the latest master branch
* [x] I've run `npm install` to install all the dependenies
* [x] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [ ] My pull request fixes an issue, I referenced the issue.
* [x] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

For example web.config in .Net Core projects
Also .pdb files from .Net

### CODE REVIEW

**Comment by jens1o** [comment]
1.8.2 is coming.

**Comment by robertohuertasm** [comment]
@jens1o, @MarcosMeli  I think I'm going to wait... 2 deliveries in less than half an hour is enough. We have lots of new icon requests and it would be nice to deliver some of them in the next release before preparing for integration.

**Comment by jens1o** [comment]
Okey, did you have a eta for the new integration? Can I do something to help you out?

**Comment by robertohuertasm** [comment]
Not really, once we have some new icons I will publish the new version. As usual, feel free to grab one of the pending issues. I'll be glad to include all your PRs :wink:

**Comment by jens1o** [comment]
Of course, I'll do it.

**Pull request merged**
