### PR TITLE
Feature angular icons

### LINKED ISSUE #437: Custom Icons for Angular 2 files
Hi there,
this is a great plugin, thanks for it.

I just thought that it would be nice to have angular icons for angular convention names for certain files. Take a look to this plugin:
https://marketplace.visualstudio.com/items?itemName=davidbabel.vscode-simpler-icons

Just for the angular conventions as I said, let's say component.ts, directive.ts, pipe.ts, service.ts and so on.

What do you think?

### PR DESCRIPTION
**Pull request by robertohuertasm**
***Fixes #437, #485 ***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] I've pulled the latest master branch.
* [ ] I've run `npm install` to install all the dependencies.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] I've run `npm run build` to build the extension.

### CODE REVIEW

**Comment by JimiC** [comment]
@robertohuertasm Looks like all `Angular` icons are missing the shadow filter. I'll fix it with a PR.

**Comment by robertohuertasm** [comment]
What shadow filter do you mean?

**Comment by JimiC** [comment]
```
<filter` id="shadow" x="-50" y="-50" width="200" height="200" name="shadow"><feOffset result="offOut" in="SourceAlpha"/><feGaussianBlur result="blurOut" stdDeviation="3" in="offOut"/><feComponentTransfer result="opacityOut" in="blurOut"><feFuncA type="linear" slope="0.5"/></feComponentTransfer></filter>
```

**Comment by JimiC** [comment]
Another issue is with the fonts (in the `js` version). They don't render correctly if the user doesn't have the font installed in their system. Saw that in `JBuilder`. I have fixed that, so I'll probably fix this also in the PR.

**Comment by robertohuertasm** [comment]
You're right. I forgot to rasterize the fonts. About the filter, see the [original angular 2 logo](https://angular.io/presskit.html). It doesn't have any shadow applied.

**Comment by JimiC** [comment]
True. I thought the shadowed version looked cooler. I can go with the official logo.

**Pull request merged**
