### PR TITLE
add travis icon

### LINKED ISSUE #185: Icon Request: .travis.yml
- [x] I want to create an icon request:
      - Icon Name: Travis CI
      - Sample original Icon(32x32/png/transparent whenever possible): https://docs.travis-ci.com/favicon.ico
      - Extensions: .travis.yml

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #185***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [ ] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

adds .travis.yml

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@jens1o change the supported extensions file addition to:
```
{ icon: 'travis', extensions: ['travis.yml'], special: 'yml' },
```

**Comment by jens1o** [comment]
done, thanks for the heads up

**Comment by Gama11** [comment]
What does the "special" do?

**Comment by robertohuertasm** [comment]
Let's say you have a file with a .js extension but you want it to have the flash icon (weird but you never know...) then using a special attribute you're saying: this is a js file but if it has the following structure (extension attribute) then assign the "icon attribute"

**Comment by robertohuertasm** [comment]
In the current case, we're saying, ok this is a yml file (special) but if it has the following form (travis.yml) don't assign .yml icon to it but instead use the travis icon.

**Comment by jens1o** [comment]
Ahhh, now it's clear. Could you add it to the CONTRIBUTION.md file?

**Comment by robertohuertasm** [comment]
I'll create a link to these thread in the Readme. ref [#201](https://github.com/robertohuertasm/vscode-icons/issues/201)

**Comment by AlexandreSNeto** [comment]
My plugin has updated (to version 1.8.3), but the icon does not apear for my file.

I think that, maybe, this line:
`{ icon: 'travis', extensions: ['travis.yml'], special: 'yml' },`
should be:
`{ icon: 'travis', extensions: ['.travis.yml'], special: 'yml' },`

Font: https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A
> Add a .travis.yml file to your repository to tell Travis CI what to build:

I have tried to create a 'travis.yml' file, to see if the icon apears correctly, but no success..

@jens1o I am doing something wrong ?

**Comment by Gama11** [comment]
>I have tried to create a 'travis.yml' file

Travis files start with a dot `.travis.yml`. For me it works: 

Have you started VSCode with admin rights so vscode-icons can install itself?

**Comment by robertohuertasm** [comment]
@AlexandreSNeto It should be working even without the dot so definitely you're missing something.

**Comment by JimiC** [comment]
**Update:**
`special` has been replaced with `contribType`.

***Example:***
```{ icon: 'travis', extensions: ['travis.yml'], special: 'yml' }```
becomes
```{ icon: 'travis', extensions: ['.travis.yml'], contribType: ctype.filename }```

**Advise:**
When you make any change to the `supportedExtensions.js` or `supportedFolders.js`, after you run the build command, if you are overwriting the existing installation of this extension in `vscode`, make sure to copy also the `icons.json` file.

**Pull request merged**
