### PR TITLE
add bower_components

### LINKED ISSUE #237: Icon request: Bower components
The folder for **Bower components** has no icon.
Website URL : [Link](https://bower.io/)
Icon that can be used : [Link](https://bower.io/img/bower-logo.svg)
Folder : **bower_components**

Thank you 😃

### PR DESCRIPTION
**Pull request by jens1o**
***Fixes #237***

**Changes proposed:**
* [X] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [X] I've pulled the latest master branch
* [ ] I've run `npm install` to install all the dependenies
* [ ] I've checked my code, it is clean.
* [ ] I've run ESLint.
* [X] My pull request fixes an issue, I referenced the issue.
* [X] My pull request is not too big, otherwise I've already squashed it.
* [ ] I've run `npm run build` to build the extension. (If I had done something with the extension.)

adds bower_components and updates the outdated icon

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @jens1o, please don't delete any icon. Rename it instead (monochrome suffix for instance). Have you respected the margins? It seems like the icon is too big, but maybe is the contrast with the old one.

**Comment by jens1o** [comment]
> Have you respected the margins?
Yes, it is 2px. The bower icon was that tiny, but I am reversing it.

**Comment by jens1o** [comment]
is it okey like this?

**Comment by robertohuertasm** [comment]
:+1: Have you renamed the old one then as I don't see the modification.  :wink:

**Comment by jens1o** [comment]
No. bower_components is a folder type, so I added the new icon as a folder type. Is it okey like this?

Look at the filename: file_type_bower@2x.png and folder_type_bower@2x.png. I think the extension is looking for the folder icon with the prefix "folder_type_", don't it?

**Comment by robertohuertasm** [comment]
Yes, you're absolutely right. My bad! Many thanks @jens1o

**Comment by robertohuertasm** [comment]
@jens1o the thing is I got confused because I didn't see any folder in the icon. I created a specific psd to create folder icons. It would be nice if all the folder icons have a folder representation. If not, it would be very difficult to spot the difference between a folder and a file. I have already merged this but I will modifiy it. :wink:

**Comment by robertohuertasm** [comment]
@jens1o is done and published. You also should have created an _opened state folder. :wink:

**Comment by jens1o** [comment]
Ah, snap. How you're creating the opened state? Do you change the alpha value?

**Comment by robertohuertasm** [comment]
The psd has already the layers created. You just have to copy one complete icon, replace the color of the folder layer and put the icon in the right lower corner. Consider some effect if the icon is not well recognized.

**Pull request merged**
