### PR TITLE
Add support for known VSCode language ids.

### PR DESCRIPTION
**Pull request by JimiC**
Relates to #522.

https://code.visualstudio.com/docs/languages/overview#_language-id

### CODE REVIEW

**Comment by JimiC** [comment]
Deliberately not marked #522 for closing to look for other via extensions supported languages .

**Comment by robertohuertasm** [comment]
Please see [this](https://github.com/robertohuertasm/vscode-icons/issues/522#issuecomment-266806258).

**Comment by JimiC** [comment]
Awaiting instruction on how to proceed.

**Comment by robertohuertasm** [comment]
Let's keep this at it is (with the new changes you applied). In case of  unsupported extensions it will be useful anyway and whenever we face a conflict or a user reports us one, we may think on how to resolve it.

I'll merge it 👍

**Pull request merged**
