### PR TITLE
Fixes eol

### PR DESCRIPTION
**Pull request by robertohuertasm**
Related to #525 

@JimiC, let me know if this works for you.

### CODE REVIEW

**Comment by JimiC** [comment]
According to Git, images are treated as binary by default.

`*.* text eol=lf` is equal to `* text eol=lf`

**Comment by JimiC** [comment]
Fetching the changes didn't created any issues with the line-breaks for me.

**Comment by robertohuertasm** [comment]
I was trying things out. Grad it also works for you. We can put it nicely in another PR.

**Comment by JimiC** [comment]
So `.gitattributes` could be modified to:

```
###############################################################################
# Set default behavior to automatically normalize line endings.
###############################################################################
* text eol=lf

###############################################################################
# Denote all files that are truly binary and should not be modified.
###############################################################################
*.psd binary
*.ai binary
```

**Pull request merged**
